export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST';
export const GET_USERS_LIST_LOADING = 'GET_USERS_LIST_LOADING';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_ERROR = 'GET_USERS_LIST_ERROR';
export const GET_USERS_LIST_RESET = 'GET_USERS_LIST_RESET';

export const CREATE_USER_REQUEST = ' CREATE_USER_REQUEST';
export const CREATE_USER_LOADING = ' CREATE_USER_LOADING';
export const CREATE_USER_SUCCESS = ' CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = ' CREATE_USER_ERROR';
export const CREATE_USER_RESET = ' CREATE_USER_RESET';

export const UPDATE_USER_REQUEST = ' UPDATE_USER_REQUEST';
export const UPDATE_USER_LOADING = ' UPDATE_USER_LOADING';
export const UPDATE_USER_SUCCESS = ' UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = ' UPDATE_USER_ERROR';
export const UPDATE_USER_RESET = ' UPDATE_USER_RESET';

export const DELETE_USER_REQUEST = ' DELETE_USER_REQUEST';
export const DELETE_USER_LOADING = ' DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = ' DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = ' DELETE_USER_ERROR';
export const DELETE_USER_RESET = ' DELETE_USER_RESET';
