export const GET_ROLES_LIST_REQUEST = 'GET_ROLES_LIST_REQUEST';
export const GET_ROLES_LIST_LOADING = 'GET_ROLES_LIST_LOADING';
export const GET_ROLES_LIST_SUCCESS = 'GET_ROLES_LIST_SUCCESS';
export const GET_ROLES_LIST_ERROR = 'GET_ROLES_LIST_ERROR';
export const GET_ROLES_LIST_RESET = 'GET_ROLES_LIST_RESET';

export const CREATE_ROLE_REQUEST = ' CREATE_ROLE_REQUEST';
export const CREATE_ROLE_LOADING = ' CREATE_ROLE_LOADING';
export const CREATE_ROLE_SUCCESS = ' CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_ERROR = ' CREATE_ROLE_ERROR';
export const CREATE_ROLE_RESET = ' CREATE_ROLE_RESET';

export const UPDATE_ROLE_REQUEST = ' UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_LOADING = ' UPDATE_ROLE_LOADING';
export const UPDATE_ROLE_SUCCESS = ' UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_ERROR = ' UPDATE_ROLE_ERROR';
export const UPDATE_ROLE_RESET = ' UPDATE_ROLE_RESET';

export const DELETE_ROLE_REQUEST = ' DELETE_ROLE_REQUEST';
export const DELETE_ROLE_LOADING = ' DELETE_ROLE_LOADING';
export const DELETE_ROLE_SUCCESS = ' DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_ERROR = ' DELETE_ROLE_ERROR';
export const DELETE_ROLE_RESET = ' DELETE_ROLE_RESET';
