export const GET_TICKETS_LIST_REQUEST = 'GET_TICKETS_LIST_REQUEST';
export const GET_TICKETS_LIST_LOADING = 'GET_TICKETS_LIST_LOADING';
export const GET_TICKETS_LIST_SUCCESS = 'GET_TICKETS_LIST_SUCCESS';
export const GET_TICKETS_LIST_ERROR = 'GET_TICKETS_LIST_ERROR';
export const GET_TICKETS_LIST_RESET = 'GET_TICKETS_LIST_RESET';

export const CREATE_TICKET_REQUEST = ' CREATE_TICKET_REQUEST';
export const CREATE_TICKET_LOADING = ' CREATE_TICKET_LOADING';
export const CREATE_TICKET_SUCCESS = ' CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_ERROR = ' CREATE_TICKET_ERROR';
export const CREATE_TICKET_RESET = ' CREATE_TICKET_RESET';

export const UPDATE_TICKET_REQUEST = ' UPDATE_TICKET_REQUEST';
export const UPDATE_TICKET_LOADING = ' UPDATE_TICKET_LOADING';
export const UPDATE_TICKET_SUCCESS = ' UPDATE_TICKET_SUCCESS';
export const UPDATE_TICKET_ERROR = ' UPDATE_TICKET_ERROR';
export const UPDATE_TICKET_RESET = ' UPDATE_TICKET_RESET';

export const DELETE_TICKET_REQUEST = ' DELETE_TICKET_REQUEST';
export const DELETE_TICKET_LOADING = ' DELETE_TICKET_LOADING';
export const DELETE_TICKET_SUCCESS = ' DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_ERROR = ' DELETE_TICKET_ERROR';
export const DELETE_TICKET_RESET = ' DELETE_TICKET_RESET';
