export const GET_PERMISSIONS_LIST_REQUEST = 'GET_PERMISSIONS_LIST_REQUEST';
export const GET_PERMISSIONS_LIST_LOADING = 'GET_PERMISSIONS_LIST_LOADING';
export const GET_PERMISSIONS_LIST_SUCCESS = 'GET_PERMISSIONS_LIST_SUCCESS';
export const GET_PERMISSIONS_LIST_ERROR = 'GET_PERMISSIONS_LIST_ERROR';
export const GET_PERMISSIONS_LIST_RESET = 'GET_PERMISSIONS_LIST_RESET';

export const CREATE_PERMISSION_REQUEST = ' CREATE_PERMISSION_REQUEST';
export const CREATE_PERMISSION_LOADING = ' CREATE_PERMISSION_LOADING';
export const CREATE_PERMISSION_SUCCESS = ' CREATE_PERMISSION_SUCCESS';
export const CREATE_PERMISSION_ERROR = ' CREATE_PERMISSION_ERROR';
export const CREATE_PERMISSION_RESET = ' CREATE_PERMISSION_RESET';

export const UPDATE_PERMISSION_REQUEST = ' UPDATE_PERMISSION_REQUEST';
export const UPDATE_PERMISSION_LOADING = ' UPDATE_PERMISSION_LOADING';
export const UPDATE_PERMISSION_SUCCESS = ' UPDATE_PERMISSION_SUCCESS';
export const UPDATE_PERMISSION_ERROR = ' UPDATE_PERMISSION_ERROR';
export const UPDATE_PERMISSION_RESET = ' UPDATE_PERMISSION_RESET';

export const DELETE_PERMISSION_REQUEST = ' DELETE_PERMISSION_REQUEST';
export const DELETE_PERMISSION_LOADING = ' DELETE_PERMISSION_LOADING';
export const DELETE_PERMISSION_SUCCESS = ' DELETE_PERMISSION_SUCCESS';
export const DELETE_PERMISSION_ERROR = ' DELETE_PERMISSION_ERROR';
export const DELETE_PERMISSION_RESET = ' DELETE_PERMISSION_RESET';
