export const GET_CLIENTS_LIST_REQUEST = 'GET_CLIENTS_LIST_REQUEST';
export const GET_CLIENTS_LIST_LOADING = 'GET_CLIENTS_LIST_LOADING';
export const GET_CLIENTS_LIST_SUCCESS = 'GET_CLIENTS_LIST_SUCCESS';
export const GET_CLIENTS_LIST_ERROR = 'GET_CLIENTS_LIST_ERROR';
export const GET_CLIENTS_LIST_RESET = 'GET_CLIENTS_LIST_RESET';
